services:
  - type: web
    name: wecom-gpt-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 wecom_openkf_gpt_bot.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
